local interval = 3
local curve    = "easeOut"

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("default",        { type = "bezier", points = { {0, 1},       {0, 1}       } })
hl.curve("wind",           { type = "bezier", points = { {0.05, 0.69}, {0.1, 1}     } })
hl.curve("winIn",          { type = "bezier", points = { {0.1, 1.1},   {0.1, 1}     } })
hl.curve("winOut",         { type = "bezier", points = { {0.3, 1},     {0, 1}       } })
hl.curve("easeOut",        { type = "bezier", points = { {0.16, 1},    {0.3, 1}     } })

hl.animation({ leaf = "border",        enabled = true, speed = 5.39,     bezier = "easeOutQuint"              })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79,     bezier = "easeOutQuint"              })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.0,      bezier = "quick"                     })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 0.8,      bezier = "quick"                     })
hl.animation({ leaf = "fade",          enabled = true, speed = 1.0,      bezier = "quick"                     })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,        bezier = "easeOutQuint", style = "fade"   })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,      bezier = "linear",       style = "fade"   })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79,     bezier = "almostLinear"              })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39,     bezier = "almostLinear"              })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 1.5,      bezier = "quick",        style = "gnomed" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.0,      bezier = "quick",        style = "gnomed" })
hl.animation({ leaf = "windowsMove",   enabled = true, speed = interval, bezier = curve,          style = "slide"  })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 2,        bezier = "easeOut",      style = "fade"   })
hl.animation({ leaf = "layers",        enabled = true, speed = 6.9,      bezier = curve,          style = "slide"  })
