-- Refer to the wiki for more information:
-- https://wiki.hypr.land/Configuring/Start/

------------------
---- PROGRAMS ----
------------------

terminal = "kitty"
fileManager = "thunar"
browser = "zen-browser"

local home = os.getenv("HOME")
local mainMod_local = "SUPER"
mainMod = mainMod_local

------------------
---- MONITORS ----
------------------

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("dms run")
	hl.exec_cmd("systemctl --user start dsearch.service")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- Scaling and cursor
hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GDK_SCALE", "1")
hl.env("GDK_DPI_SCALE", "1")
hl.env("QT_SCALE_FACTOR", "1")

-- XDG
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- NVIDIA
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")

-- Wayland
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 4,

		border_size = 2,

		-- DMS overrides these at runtime; values below are the fallback
		col = {
			active_border = "rgb(cba6f7)",
			inactive_border = "rgb(6c7086)",
		},

		resize_on_border = true,
		extend_border_grab_area = 20,
		allow_tearing = false,
		layout = "dwindle",
	},

	cursor = {
		no_hardware_cursors = true,
	},

	decoration = {
		rounding = 6,
		rounding_power = 2,

		active_opacity = 1,
		inactive_opacity = 0.9,

		shadow = {
			enabled = true,
			range = 1,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},

		blur = {
			enabled = true,
			size = 2,
			passes = 4,
			new_optimizations = true,
			vibrancy = 0.1696,
		},
	},

	animations = { enabled = true },

	dwindle = {
		preserve_split = true,
		split_width_multiplier = 1.2,
	},

	master = {
		new_status = "master",
	},

	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
		mouse_move_enables_dpms = false,
	},

	input = {
		kb_layout = "br",
		kb_variant = "abnt2",
		kb_model = "abnt2",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,
		mouse_refocus = false,
		sensitivity = 0.5,

		touchpad = {
			natural_scroll = true,
			disable_while_typing = false,
		},
	},
})

-- DMS: group border colors (auto-generated by DMS; update if theme changes)
hl.config({
	group = {
		col = {
			border_active = "rgb(cba6f7)",
			border_inactive = "rgb(6c7086)",
			border_locked_active = "rgb(f38ba8)",
			border_locked_inactive = "rgb(6c7086)",
		},
		groupbar = {
			col = {
				active = "rgb(cba6f7)",
				inactive = "rgb(6c7086)",
				locked_active = "rgb(f38ba8)",
				locked_inactive = "rgb(6c7086)",
			},
		},
	},
})

---------------
---- INPUT ----
---------------

-- Gestures
hl.gesture({ fingers = 4, direction = "vertical", action = "workspace" })
hl.gesture({ fingers = 3, direction = "swipe", action = "move" })

hl.device({ name = "epic-mouse-v1", sensitivity = -0.6 })

----------------------------------
---- WINDOW / WORKSPACE RULES ----
----------------------------------

-- Smart gaps (no borders when only one window)
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
hl.window_rule({ match = { float = false, workspace = "w[tv1]" }, border_size = 0, rounding = 0 })
hl.window_rule({ match = { float = false, workspace = "f[1]" }, border_size = 0, rounding = 0 })

-- Center all floating windows by default
hl.window_rule({ match = { class = ".*" }, center = true })

-- File Manager
hl.window_rule({ match = { class = fileManager }, float = true, move = "20 70", size = "800 600" })

-- Terminal
hl.window_rule({ match = { class = terminal }, size = "1000 600" })

-- Browser
hl.window_rule({ match = { class = browser }, float = true })

-- Fix drag issues with XWayland
hl.window_rule({
	match = { xwayland = true, class = "^$", title = "^$", float = true, fullscreen = false, pin = false },
	no_focus = true,
})

-- Steam
hl.window_rule({ match = { class = "^steam_app%d+$" }, fullscreen = true, monitor = 1, workspace = 10 })

-----------------
---- MODULES ----
-----------------

require("animations")
require("bindings")
