# Some personal options
cursor_trail 200
cursor_trail_decay 0.05 0.2
cursor_shape block
scrollback_lines 10000
mouse_hide_wait 2.0
detect_urls always

# Remote control to change colors via pywal
allow_remote_control yes

# Allow hyperlinks
allow_hyperlinks yes

# Nerd Fonts v3.3.0, extend some nerd icons
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

# background blur
background_blur 1

# background / transparency
background_opacity 0.8
hide_window_decorations yes

# Fonts
font_size 12

# Enable multi-caracter selection
map ctrl+shift+left mouse_selection rectangle
copy_on_select no

# Navigate between tabs
map ctrl+shift+left previous_tab
map ctrl+shift+right next_tab

# Open/close window
map ctrl+shift+q close_tab
map ctrl+w close_window

# Split window
map ctrl+shift+enter launch --location=hsplit --cwd=current
map ctrl+enter launch --location=vsplit --cwd=current

# Copy/Paste clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+v paste_from_clipboard

# Font zoom
map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# Dinamic background opacity change
dynamic_background_opacity yes
map ctrl+alt+o set_background_opacity +0.1
map ctrl+shift+alt+o set_background_opacity -0.1


# IMPORTING COLORS FROM PYWAL
# include ~/.cache/wal/colors-kitty.conf

# Fonts
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Colors
include  ~/.config/kitty/colors.conf
